### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by danbim** [Taig/circe-validation#1]
It would be great to have a cross-build for Scala 2.13. circe-validation is one of the last libs in my dependency tree not available for Scala 2.13

**Comment by taig** [comment]
Hi @danbim,
thank your for the PR. I'll look into it shortly and publish a new release. I wasn't aware people were using this, especially as this is a somewhat experimental exploration. In the long run you might be better off with a fork though or by copying the tiny codebase into you project.

**Comment by taig** [comment]
Version 0.2.0 with your changes is on its way to maven central. In the future it will be easier to cut a new release and I will get @scala-steward involved. Thank you for the PR!

**Comment by danbim** [comment]
Thanks Niklas for the quick merge :)

Btw... your new microsite certificate seems to be invalid.

**Comment by taig** [comment]
Thanks it appears like GitLab is still obtaining the certificate. I'll wait a little longer 🙏
